version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    container_name: app

  db:
    image: postgres:13
    container_name: db
    # only to pass hexlet ci step
    env_file: test.env
