version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    container_name: app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    # only to pass hexlet ci step
    environment:
      - POSTGRES_USER=${NODOS_DB_USERNAME}
      - POSTGRES_PASSWORD=${NODOS_DB_PASSWORD}
