version: "3.8"

services:
  app:
    build: Dockerfile.production
    command: npm test
    container_name: app
    volumes:
      - "./:/app"

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
